{{ if .Values.configuration.custom_ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-custom-ca
  labels: {{- include "sentinelone.agent.labels" . | nindent 4 }}
type: Opaque
data: {{- include "agent.certificates" . | nindent 2 -}}
{{- end -}}

