apiVersion: v1
kind: Service
metadata:
  name: {{ include "helper.fullname" . }}
  labels: {{- include "sentinelone.helper.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
        {{- include "sentinelone.helper.selector.labels" . | nindent 4 }}
