apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
  labels: {{- include "sentinelone.helper.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  namespace: {{ include "namespace" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "service.port" . }}
      targetPort: {{ include "service.target_port" . }}
      protocol: TCP
      name: https
  selector:
        {{- include "sentinelone.helper.selector.labels" . | nindent 4 }}
