{{- if include "custom_ca.secret.create" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "custom_ca.secret.name" . }}
  labels: {{- include "sentinelone.agent.labels" . | nindent 4 }}
type: Opaque
{{- $agentCerts := fromYaml (include "agent.certificates" .) }}
data:
{{- range $cert := $agentCerts.certificates }}
  {{- $cert.name | nindent 2 }}: {{ $cert.data }}
{{- end -}}
{{- end -}}
