{{ if .Values.configuration.env.injection.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentInjection.name" . }}
  labels:
    {{- include "sentinelone.agent.labels" . | nindent 4 }}
  namespace: {{ include "namespace" . }}
data:
  config.yaml: |
    metadata:
      labels:
        {{- include "sentinelone.agent.selector.labels" . | nindent 8 }}
    spec:
  {{- if .Values.secrets.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.secrets.imagePullSecret }}
  {{- end }}
      shareProcessNamespace: true
      containers:
        {{- include "serverlessAgentContainer" . | nindent 8 }}
          - name: S1_HELPER_HOST
            value: {{ include "service.name" . }}.{{ include "namespace" . }}
          - name: S1_AGENT_CONFIG_FILE
            value: "/{{ include "agent.fullname" . }}/config.yaml"
          volumeMounts:
          - name: {{ include "agent.fullname" . }}
            mountPath: /{{ include "agent.fullname" . }}
      volumes:
      - name: {{ include "agent.fullname" . }}
        configMap:
          name: {{ include "agent.fullname" . }}
{{ end }}

---

{{ if or (not .Values.configuration.env.injection.enabled) (eq (include "serverlessOnlyMode" .) "false") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname" . }}-config
  labels:
    {{- include "sentinelone.agent.labels" . | nindent 4 }}
  namespace: {{ include "namespace" . }}
data:
{{- with .Values.configuration }}
{{- range $name, $conf := dict "local.conf" .localConf "override.conf" .overrideConf }}
{{- if $conf }}
  {{ $name }}: |
  {{- if kindIs "map" $conf }}
    {{- mustToPrettyJson $conf | nindent 4 }}
  {{ else }}
    {{- $conf | nindent 4 }}
  {{ end }}
{{- end }}
{{- end }}
{{ end }}
{{ end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helper.fullname" . }}-config
  labels:
    {{- include "sentinelone.helper.labels" . | nindent 4 }}
  namespace: {{ include "namespace" . }}
data:
  {{- include "helper.config" . | nindent 2 }}
