{{ if .Values.configuration.env.injection.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentInjection.name" . }}
  labels:
    {{- include "sentinelone.agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    metadata:
      labels:
        {{- include "sentinelone.agent.selector.labels" . | nindent 8 }}
    spec:
  {{- if .Values.secrets.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.secrets.imagePullSecret }}
  {{- end }}
      shareProcessNamespace: true
      containers:
        {{- include "serverlessAgentContainer" . | nindent 8 }}
          - name: S1_HELPER_HOST
            value: {{ include "service.name" . }}.{{ .Release.Namespace }}
          - name: S1_AGENT_CONFIG_FILE
            value: "/{{ include "agent.fullname" . }}/config.yaml"
          volumeMounts:
          - name: {{ include "agent.fullname" . }}
            mountPath: /{{ include "agent.fullname" . }}
      volumes:
      - name: {{ include "agent.fullname" . }}
        configMap:
          name: {{ include "agent.fullname" . }}
{{ end }}
