{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinelone.serviceAccountName" . }}
  labels:
    {{- include "sentinelone.agent.labels" . | nindent 4 }}
  annotations: {{- include "helper.rbac.annotations" . | nindent 4 }}
    {{ if eq (include "argocdPostDeleteHook.enabled" .) "true" }}
    "argocd.argoproj.io/sync-options": Delete=false
    {{- end -}}
{{- end -}}
