{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinelone.serviceAccountName" . }}
  labels:
    {{- include "sentinelone.agent.labels" . | nindent 4 }}
{{- end -}}
