{{ if .Values.helper.rbac.create }}
apiVersion: {{ template "clusterRole.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "helper.rbac.name" . }}
  labels: {{- include "sentinelone.helper.labels" . | nindent 4 }}
  annotations: {{- include "helper.rbac.annotations" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces", "replicationcontrollers"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch", "apps"]
  resources: ["jobs", "deployments", "daemonsets", "replicasets", "statefulsets", "crontabs"]
  verbs: ["get", "watch", "list"]
{{ if .Values.configuration.env.injection.enabled }}
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list", "update", "create", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
{{ if eq (include "serverlessOnlyMode" .) "true" }}
- apiGroups: ["*"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "watch", "list", "delete"]
{{ end }}
{{ end }}
{{ end }}
