{{ if .Values.helper.rbac.create }}
apiVersion: {{ template "clusterRole.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "helper.fullname" . }}
  labels: {{- include "sentinelone.agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces", "replicationcontrollers"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["batch", "apps"]
  resources: ["jobs", "deployments", "daemonsets", "replicasets", "statefulsets", "crontabs"]
  verbs: ["get", "watch", "list"]
{{ if .Values.configuration.env.injection.enabled }}
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
{{ end }}
{{ end }}
