{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "sentinelone.helper.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.agent.env.site_key }}
  site-key: {{ .Values.agent.env.site_key | b64enc | quote }}
  {{- end }}
{{- end -}}
