apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  labels:
    {{- include "sentinelone.helper.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
        {{- include "sentinelone.helper.selector.labels" . | nindent 4 }}