{{- if and
  (or
    (not .Values.configuration.env.injection.enabled)
    (eq (include "serverlessOnlyMode" .) "false")
  )
  (not .Values.configuration.inventory_only)
  (eq .Values.configuration.deployment_type "argocd")
}}
apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-post-delete-hook
  labels:
{{ include "sentinelone.helper.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/hook": PostDelete
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "sentinelone.helper.labels" . | nindent 8 }}
      name: argocd-post-delete-hook
    spec:
{{- if .Values.secrets.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.secrets.imagePullSecret }}
{{- end }}
      restartPolicy: Never
      serviceAccountName: {{ include "sentinelone.serviceAccountName" . }}
      containers:
        - name: argocd-post-delete-hook
          image: "{{ include "helper.full_url" . }}"
          command: [ "/bin/bash", "-c" ]
          args:
            - >
              tar xzf /s1-helper/kubectl.tar.gz -C /;
              /s1-helper/kubectl get pods --no-headers --field-selector status.phase=Running -o custom-columns=':metadata.name' |
                grep {{ include "helper.fullname" . }} |
                  xargs -I _ bash -c 'for i in {1..3}; do
                    /s1-helper/kubectl exec _ -- bash -c "touch /s1-helper/uninstall-started && killall -SIGUSR1 s1-helper-app" 2>&1 && exit 0 || sleep 1; done';
              for i in {1..2}; do
                /s1-helper/kubectl get pods --no-headers --field-selector status.phase=Running -o custom-columns=':metadata.name' |
                  grep {{ include "agent.fullname" . }} |
                    xargs -P 0 -I % bash -c '
                      out=$(for i in {1..3}; do
                              timeout 10 /s1-helper/kubectl exec % -- bash -c "
                                    sudo test -f /opt/sentinelone/tmp/uninstall_started && echo Already uninstalled || sudo sentinelctl control uninstall
                                " && exit 0 || sleep 2;
                            done;
                            exit 1
                      ) && echo -e "\nSuccess For Pod %:\n$out" || (echo -e "\nError For Pod %:\n$out" && exit 1)'
                if [[ $? == 0 ]]; then break; fi
                echo -e "\n----------------------------------\n";
                sleep 1;
              done;
              /s1-helper/kubectl delete daemonset {{ include "agent.fullname" . }} --ignore-not-found;
              /s1-helper/kubectl delete serviceaccount {{ include "sentinelone.serviceAccountName" . }} --ignore-not-found;
              echo "Done";
{{ end }}
