{{ if eq (include "argocdPostDeleteHook.enabled" .) "true" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "argocdPostDeleteHook.name" . }}
  labels:
{{ include "sentinelone.helper.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/hook": PostDelete
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded, BeforeHookCreation, HookFailed
spec:
  backoffLimit: 0
  activeDeadlineSeconds: {{ .Values.configuration.argocd.post_delete_hook_timeout }}
  template:
    metadata:
      labels:
        {{- include "sentinelone.helper.labels" . | nindent 8 }}
      name: {{ include "argocdPostDeleteHook.name" . }}
    spec:
{{- if .Values.secrets.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.secrets.imagePullSecret }}
{{- end }}
      restartPolicy: Never
      serviceAccountName: {{ include "sentinelone.serviceAccountName" . }}
      containers:
        - name: {{ include "argocdPostDeleteHook.name" . }}
          securityContext:
            {{- toYaml .Values.helper.securityContext | nindent 12 }}
          image: "{{ include "helper.full_url" . }}"
          command: [ "s1-helper-app" ]
          env:
            {{- include "hooks.uninstallEnv" . | nindent 12 }}
            - name: ARGOCD_MODE
              value: "true"
            - name: S1_UNINSTALL_DELETE_SA
              value: "{{ or (not .Values.configuration.env.injection.enabled) (eq (include "serverlessOnlyMode" .) "false") }}"
{{ end }}
