{{- if and
  .Values.serviceAccount.create
  (or
    (eq (include "argocdPostDeleteHook.enabled" .) "true")
    (eq (include "preDeleteHook.enabled" .) "true")
  )
-}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinelone.serviceAccountName" . }}-delete-hook
  labels:
    {{- include "sentinelone.agent.labels" . | nindent 4 }}
  annotations:
    {{- include "helper.rbac.annotations" . | nindent 4 }}
    {{ if eq (include "argocdPostDeleteHook.enabled" .) "true" }}
    "argocd.argoproj.io/hook": PostDelete
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded, BeforeHookCreation, HookFailed
    {{- end -}}
{{- end -}}
