{{ if eq (include "preDeleteHook.enabled" .) "true" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "preDeleteHook.name" . }}
  labels:
{{ include "sentinelone.helper.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "sentinelone.helper.labels" . | nindent 8 }}
      name: {{ include "preDeleteHook.name" . }}
    spec:
{{- if .Values.secrets.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.secrets.imagePullSecret }}
{{- end }}
      restartPolicy: Never
      serviceAccountName: {{ include "sentinelone.serviceAccountName" . }}
      containers:
        - name: {{ include "preDeleteHook.name" . }}
          image: "{{ include "helper.full_url" . }}"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          command: [ "/bin/bash", "-c" ]
          args:
            - |
              {{ include "hooks.uninstallScript" . | nindent 14 }}
              echo "Done";
{{ end }}
