apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-uninstall-agent-job"
  labels:
{{ include "sentinelone.helper.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "sentinelone.helper.labels" . | nindent 8 }}
      name: uninstall-agent
    spec:
{{- if .Values.secrets.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.secrets.imagePullSecret }}
{{- end }}
      restartPolicy: Never
      serviceAccountName: {{ include "sentinelone.serviceAccountName" . }}
      containers:
        - name: uninstall-agent
          image: "{{ include "helper.full_url" . }}"
          command: [ "/bin/sh", "-c" ]
          args:
            - >
              /s1-helper/kubectl get pods --no-headers --field-selector status.phase=Running -o custom-columns=':metadata.name' |
              grep {{ include "agent.fullname" . }} |
              xargs -P 0 -I _ sh -c 'out=$(for i in {1..5}; do /s1-helper/kubectl exec _ -- sudo sentinelctl control uninstall 2>&1 && break || sleep 3; done) || rc=$? && echo -e "\nPod _:\n$out" && exit $rc; echo -e "\nPod _:\n$out"'
