{{ if include "preDeleteHook.enabled" . }}
apiVersion: {{ template "clusterRoleBindings.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ include "preDeleteHook.name" . }}
  labels: {{- include "sentinelone.agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "preDeleteHook.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "sentinelone.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
